spring:
  datasource:
    url: jdbc:mysql://3.37.194.187:3306/dish2?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nori
    password:

